site_name: Wildlife Datasets

theme:
  name: "material"

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [wildlife_datasets]
    
nav:
  - Introduction: index.md
  - Oveview of datasets: datasets.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - Reference datasets: reference_datasets.md
  - Reference utils: reference_utils.md
