site_name: Wildlife Datasets

theme:
  name: "material"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [wildlife_datasets]
    
nav:
  - Introduction: index.md  
  - Installation: installation.md
  - Oveview of datasets: datasets.md
  - Dataset description: dataframe.md
  - Tutorial - datasets: tutorial_datasets.md
  - Tutorial - splits: tutorial_splits.md
  - Tutorial - evaluation: tutorial_evaluation.md
  - Adding new datasets: adding.md
  - Reference - datasets: reference_datasets.md
  - Reference - utils: reference_utils.md
  - Reference - splits: reference_splits.md
  - Reference - evaluation: reference_evaluation.md
