site_name: Wildlife Datasets

theme:
  name: "material"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [wildlife_datasets]
    
nav:
  - Introduction: index.md  
  - Oveview of datasets: datasets.md
  - Installation: installation.md
  - Tutorial - datasets: tutorial_datasets.md
  - Tutorial - splits: tutorial_splits.md
  - Adding new datasets: adding.md
  - Reference datasets: reference_datasets.md
  - Reference utils: reference_utils.md
