[project]
name = "Wildlife datasets"
version = "0.0.1"
authors = [
  { name="Vojtech Cermak", email="cermak.vojtech@seznam.cz" },
  { name="Lukas Adam", email="lukas.adam.cr@gmail.com" },
]
description = "Library for easier access andresearch of wildlife datasets"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/WildlifeDatasets/wildlife-datasets"
"Bug Tracker" = "https://github.com/WildlifeDatasets/wildlife-datasets/issues"